import mantineTheme from "@/theme/mantineTheme";
import "@mantine/charts/styles.css";
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import "@mantine/core/styles.css";
import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <RootStyleRegistry>
          <MantineProvider
            defaultColorScheme="dark"
            stylesTransform={emotionTransform}
            theme={mantineTheme}
          >
            <MantineEmotionProvider>{children}</MantineEmotionProvider>
          </MantineProvider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
